logging:
  console:
    level: 'DEBUG'
  file:
    level: 'DEBUG'
    filename: 'iet.log'

bootstrap:
  default:
    dirs:
      - Reporting
      - wip
      - wip/screenshots
      - project-files
      - .logging
    files:
      basedir:
        - res/.in
        - res/.out
      wip:
        - res/testfile
    vars:
      - nessus_url
      - ssh_port
