logging:
  console:
    level: 'DEBUG'
  file:
    level: 'DEBUG'
    filename: 'iet.log'

bootstrap:
  default:
    dirs:
      - Reporting
      - wip
      - wip/nmap
      - wip/nessus
      - wip/gobuster
      - wip/screenshots
      - project-files
      - .logging
    files:
      basedir:
        - res/.in
        - res/.out
    vars:
      - nessus_url
      - ssh_port
  segmentation-test:
    dirs:
      - Reporting
      - wip
      - wip/nmap
      - project-files
      - .logging
    files:
      basedir:
        - res/.in
        - res/.out
    vars:
      - ssh_port
  barebones:
    dirs:
      - .logging
    files:
      basedir:
        - res/.in
        - res/.out
    vars:
        - ssh_port
  mobile-app:
    dirs:
      - Reporting
      - wip/android
      - wip/ios
      - src/android
      - src/ios
      - project-files
      - app-packages
      - .logging
    files:
      basedir:
        - res/mobile-app/.in
        - res/mobile-app/.out
    vars:
      - nessus_url
      - package_name

wordlists:
  month_spread: 5
  end_characters: '!.'
  seasons:
    spring:
      - 3
      - 4
      - 5
    summer:
      - 6
      - 7
      - 8
    fall:
      - 9
      - 10
      - 11
    winter:
      - 12
      - 1
      - 2
