logging:
  console:
    level: 'DEBUG'
  file:
    level: 'DEBUG'
    filename: 'iet.log'

bootstrap:
  default:
    dirs:
      - Reporting
      - wip
      - wip/screenshots
      - project-files
      - .logging
    files:
      basedir:
        - res/.in
        - res/.out
      wip:
        - res/testfile
    vars:
      - nessus_url
      - ssh_port

passwords:
  month_spread: 5
  end_characters: '!.'
  seasons:
    spring:
      - 3
      - 4
      - 5
    summer:
      - 6
      - 7
      - 8
    fall:
      - 9
      - 10
      - 11
    winter:
      - 12
      - 1
      - 2
